bugiardini_blog_homepage:
    path:     /
    defaults: { _controller: BugiardiniBlogBundle:Page:index }
    requirements:
         _method:  GET
         
bugiardini_blog_about:
    path:     /chi_siamo
    defaults: { _controller: BugiardiniBlogBundle:Page:about }
    requirements:
         _method:  GET

